# Generated by Django 4.1.7 on 2024-04-15 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone_book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.IntegerField(unique=True),
        ),
    ]
